branches:
  only: main
Alanguage: node_js
node_js:
  - 14
before_script:
  - npm install @11ty/eleventy -g
script: eleventy
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY_ID
  bucket: $BUCKET
  regeion: $AWS_REGION
  local_dir: _site/
  skip_cleanup: true
  on:
    main
