language: node_js
node_js:
  - 14
before_script:
  - npm install @11ty/eleventy -g
script: eleventy
deploy:
  provider: s3
  access_key_id: "AKIAVHOZJ7SJX327XCHZ"
  secret_access_key: "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"
  bucket: "logs.minsan.xyz"
  region:  "ap-southeast-1"
  skip_cleanup: true
  local_dir: _site/
  on:
    branch: main
